-- Insertion des valeurs dans la table animaux:
INSERT INTO animaux (nom_animal, espèce, alimentation, image, paysorigine, description_animal, habitat_id) VALUES

("Lion d'Afrique",
 'Panthera leo',
 'Carnivore',
 'https://images.unsplash.com/photo-1516734212186-a967f81ad32f',
 'Kenya',
 'Grand félin vivant en groupes appelés hardes, au sommet de la chaîne alimentaire de la savane africaine.',
 1),

('Girafe réticulée',
 'Giraffa camelopardalis reticulata',
 'Herbivore',
 'https://images.unsplash.com/photo-1508672019048-805c876b67e2',
 'Kenya',
 'Très grande girafe aux motifs de pelage bien délimités, vivant dans les savanes et zones semi-arides d’Afrique de l’Est.',
 1),

('Zèbre des plaines',
 'Equus quagga',
 'Herbivore',
 'https://images.unsplash.com/photo-1516455207990-7a41ce80f7ee',
 'Tanzanie',
 'Équidé rayé noir et blanc vivant en troupeaux, bien adapté aux savanes ouvertes africaines.',
 1),

('Gorille des plaines',
 'Gorilla gorilla',
 'Herbivore',
 'https://images.unsplash.com/photo-1524805444758-089113d48a6d',
 'Congo',
 'Grand singe puissant et principalement herbivore, vivant en groupes familiaux dans les forêts tropicales africaines.',
 2),

('Perroquet gris du Gabon',
 'Psittacus erithacus',
 'Herbivore',
 'https://images.unsplash.com/photo-1525253013412-55c1a69a5738',
 'Gabon',
 'Perroquet africain célèbre pour son intelligence et sa capacité exceptionnelle à imiter la voix humaine.',
 2),

('Fennec',
 'Vulpes zerda',
 'Omnivore',
 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13',
 'Maroc',
 'Petit renard du Sahara doté de très grandes oreilles qui l’aident à réguler sa température corporelle et à repérer ses proies.',
 3),

('Addax',
 'Addax nasomaculatus',
 'Herbivore',
 'https://images.unsplash.com/photo-1525610553991-2bede1a236e2',
 'Niger',
 'Antilope du désert très adaptée aux milieux arides, capable de supporter de longues périodes sans eau.',
 3),

('Hippopotame',
 'Hippopotamus amphibius',
 'Herbivore',
 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131',
 'Zambie',
 'Grand mammifère semi-aquatique passant la plupart de la journée dans l’eau pour se protéger de la chaleur.',
 5),

('Crocodile du Nil',
 'Crocodylus niloticus',
 'Carnivore',
 'https://images.unsplash.com/photo-1509099863731-ef4bff19e808',
 'Égypte',
 'Important prédateur des rivières et lacs africains, connu pour sa puissance et son mode de chasse à l’affût.',
 5),

('Python royal',
 'Python regius',
 'Carnivore',
 'https://images.unsplash.com/photo-1516715094483-75da7dee9758',
 'Ghana',
 'Serpent constricteur non venimeux, souvent surnommé « python boule » en raison de sa tendance à se rouler en boule.',
 9),

('Caméléon panthère',
 'Furcifer pardalis',
 'Carnivore',
 'https://images.unsplash.com/photo-1516714435131-44d6b64dc6a5',
 'Madagascar',
 'Lézard connu pour ses couleurs vives et sa capacité à changer de teinte, vivant dans la végétation dense des zones tropicales.',
 9);